'use strict';
const inPages=location.pathname.includes('/pages/'), root=inPages?'../':'';
const products=[
 {id:1,name:'MG Crimson Wing 1/100',category:'Gundam',price:1250000,image:'assets/products/mecha.png',tag:'BEST SELLER',stock:8,desc:'Mecha lắp ráp tỉ lệ 1/100, khung chi tiết và phối màu đỏ trắng nổi bật.',scale:'1/100',material:'Nhựa ABS / PS'},
 {id:2,name:'Explorer Series Orange',category:'Figure',price:1680000,image:'assets/products/figure.png',tag:'NEW',stock:4,desc:'Figure PVC nguyên bản với phụ kiện thám hiểm và đế trưng bày hoàn thiện.',scale:'1/7',material:'PVC / ABS'},
 {id:3,name:'Blue Apex Racing 1/24',category:'Diecast',price:890000,image:'assets/products/diecast.png',tag:'HOT',stock:12,desc:'Xe diecast kim loại với nội thất mô phỏng và bánh xe chuyển động.',scale:'1/24',material:'Kim loại / ABS'},
 {id:4,name:'RG Scarlet Frame 1/144',category:'Gundam',price:1320000,image:'assets/products/mecha.png',tag:'',stock:6,desc:'Mẫu mecha khung RG nhỏ gọn với độ chi tiết cao.',scale:'1/144',material:'Nhựa ABS / PS'},
 {id:5,name:'Camp Edition Figure',category:'Figure',price:1090000,image:'assets/products/figure.png',tag:'NEW',stock:5,desc:'Figure phiên bản dã ngoại, màu sắc ấm và nhiều phụ kiện nhỏ.',scale:'1/8',material:'PVC / ABS'},
 {id:6,name:'Apex Racing Mini 1/64',category:'Diecast',price:420000,image:'assets/products/diecast.png',tag:'',stock:0,desc:'Xe mô hình đua kích thước 1/64 dành cho tủ trưng bày.',scale:'1/64',material:'Kim loại / ABS'}
];
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)], money=n=>new Intl.NumberFormat('vi-VN').format(n)+'₫';
let filter=new URLSearchParams(location.search).get('category')||'Tất cả', query='', sort='featured', cart=loadCart();
function loadCart(){try{return JSON.parse(localStorage.getItem('dna-cart'))||{}}catch{return {}}}
function saveCart(){localStorage.setItem('dna-cart',JSON.stringify(cart))}
function notify(text){const toast=$('#toast');if(!toast)return;toast.textContent=text;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),1700)}
function filteredProducts(){let list=products.filter(p=>(filter==='Tất cả'||p.category===filter)&&p.name.toLowerCase().includes(query.toLowerCase()));if(sort==='price-asc')list.sort((a,b)=>a.price-b.price);if(sort==='price-desc')list.sort((a,b)=>b.price-a.price);if(sort==='name')list.sort((a,b)=>a.name.localeCompare(b.name,'vi'));return list}
function productCard(p){const el=document.createElement('article');el.className='product';el.innerHTML=`<a class="product-view" href="${inPages?'':'pages/'}product-detail.html?id=${p.id}" aria-label="Xem ${p.name}"><img src="${root+p.image}" alt="${p.name}" loading="lazy"></a>${p.tag?`<span class="tag">${p.tag}</span>`:''}<div class="info"><small>${p.category}</small><h3><a href="${inPages?'':'pages/'}product-detail.html?id=${p.id}">${p.name}</a></h3><p class="stock ${p.stock?'':'out'}">${p.stock?'Còn '+p.stock+' sản phẩm':'Tạm hết hàng'}</p><div class="price"><b>${money(p.price)}</b><button class="add" data-add="${p.id}" ${p.stock?'':'disabled'} aria-label="Thêm ${p.name}">+</button></div></div>`;return el}
function renderProducts(){const grid=$('#product-grid');if(!grid)return;let list=filteredProducts();if(document.body.dataset.page==='detail'){const current=+new URLSearchParams(location.search).get('id');list=list.filter(p=>p.id!==current)}const limit=+grid.dataset.limit||list.length;grid.replaceChildren(...list.slice(0,limit).map(productCard));if(!list.length){const p=document.createElement('p');p.textContent='Không tìm thấy sản phẩm phù hợp.';grid.append(p)}}
function change(id,delta){const p=products.find(x=>x.id===id);if(!p||!p.stock)return;cart[id]=Math.max(0,Math.min(p.stock,(cart[id]||0)+delta));if(!cart[id])delete cart[id];saveCart();renderCart()}
function renderCart(){const count=$('#cart-count'),box=$('#cart-items'),total=$('#cart-total');if(!count||!box||!total)return;const rows=Object.entries(cart).map(([id,q])=>[products.find(p=>p.id===+id),q]).filter(x=>x[0]);count.textContent=rows.reduce((s,x)=>s+x[1],0);box.replaceChildren();if(!rows.length){const p=document.createElement('p');p.className='empty';p.textContent='Giỏ hàng đang trống. Hãy chọn một món thật ngầu nhé!';box.append(p)}else rows.forEach(([p,q])=>{const el=document.createElement('div');el.className='item';el.innerHTML=`<img class="thumb" src="${root+p.image}" alt=""><div><h3>${p.name}</h3><p>${money(p.price)}</p><div class="quantity"><button data-change="-1" data-id="${p.id}">−</button><b>${q}</b><button data-change="1" data-id="${p.id}">+</button><button class="remove" data-remove="${p.id}">Xóa</button></div></div>`;box.append(el)});total.textContent=money(rows.reduce((s,[p,q])=>s+p.price*q,0))}
function drawer(show){$('#drawer')?.classList.toggle('open',show);$('#overlay')?.classList.toggle('open',show);document.body.classList.toggle('locked',show)}
function renderDetail(){const host=$('#detail-page');if(!host)return;const id=Number(new URLSearchParams(location.search).get('id')),p=products.find(x=>x.id===id);if(!p){host.innerHTML='<div class="not-found"><h1>Không tìm thấy sản phẩm</h1><a class="primary" href="products.html">Về danh sách →</a></div>';return}document.title=p.name+' | DNA Hobby Store';$('#crumb').textContent=p.name;host.innerHTML=`<div class="detail-gallery"><img src="${root+p.image}" alt="${p.name}"></div><div class="detail-copy"><p class="kicker">${p.category} / ${p.tag||'DNA SELECTED'}</p><h1>${p.name}</h1><b class="detail-price">${money(p.price)}</b><p class="detail-desc">${p.desc}</p><dl><div><dt>Tỉ lệ</dt><dd>${p.scale}</dd></div><div><dt>Chất liệu</dt><dd>${p.material}</dd></div><div><dt>Tình trạng</dt><dd>${p.stock?'Còn hàng':'Tạm hết hàng'}</dd></div></dl><div class="detail-buy"><button class="primary" data-add="${p.id}" ${p.stock?'':'disabled'}>Thêm vào giỏ →</button><span>${p.stock?'Còn '+p.stock+' sản phẩm':'Sản phẩm đang hết hàng'}</span></div><p class="shipping-note">✓ Đóng gói chuẩn collector　✓ Đổi trả trong 7 ngày</p></div>`}
document.addEventListener('click',e=>{const add=e.target.closest('[data-add]');if(add){change(+add.dataset.add,1);notify('Đã thêm vào giỏ hàng')}if(e.target.dataset.change)change(+e.target.dataset.id,+e.target.dataset.change);if(e.target.dataset.remove){delete cart[e.target.dataset.remove];saveCart();renderCart()}});
$('.filters')?.addEventListener('click',e=>{if(!e.target.dataset.filter)return;filter=e.target.dataset.filter;$$('.filters button').forEach(b=>b.classList.toggle('active',b.dataset.filter===filter));history.replaceState({},'',filter==='Tất cả'?'products.html':'?category='+encodeURIComponent(filter));renderProducts()});
$('#search-input')?.addEventListener('input',e=>{query=e.target.value.slice(0,60);renderProducts()});$('#sort')?.addEventListener('change',e=>{sort=e.target.value;renderProducts()});
$('#cart-toggle')?.addEventListener('click',()=>drawer(true));$('#close-cart')?.addEventListener('click',()=>drawer(false));$('#overlay')?.addEventListener('click',()=>drawer(false));$('#menu')?.addEventListener('click',()=>$('#nav').classList.toggle('open'));
$('#checkout')?.addEventListener('click',()=>{if(!Object.keys(cart).length)return notify('Giỏ hàng đang trống');const dialog=$('#checkout-dialog');drawer(false);dialog?dialog.showModal():notify('Checkout sẽ được nối với backend sau')});
$$('[data-close]').forEach(b=>b.addEventListener('click',()=>$('#'+b.dataset.close).close()));$('#checkout-form')?.addEventListener('submit',e=>{e.preventDefault();cart={};saveCart();renderCart();$('#checkout-dialog').close();e.target.reset();notify('Đơn hàng mẫu đã được xác nhận')});
$$('.filters button').forEach(b=>b.classList.toggle('active',b.dataset.filter===filter));renderDetail();renderProducts();renderCart();
