'use strict';
const inPages=location.pathname.includes('/pages/'),root=inPages?'../':'', $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const money=n=>new Intl.NumberFormat('vi-VN').format(n)+'₫', esc=s=>String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const fallback='data:image/svg+xml;charset=UTF-8,'+encodeURIComponent('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 600 600"><rect width="600" height="600" fill="#e8e5df"/><text x="300" y="290" text-anchor="middle" font-family="sans-serif" font-size="34" fill="#70716f">DNA HOBBY</text><text x="300" y="335" text-anchor="middle" font-family="sans-serif" font-size="16" fill="#70716f">Ảnh đang cập nhật</text></svg>');
let products=[],cart=loadCart(),filter=new URLSearchParams(location.search).get('category')||'Tất cả',query='',sort='featured',price='all',brand='all',scale='all',inStock=false,visible=8;
function loadCart(){try{return JSON.parse(localStorage.getItem('dna-cart'))||{}}catch{return {}}} function saveCart(){localStorage.setItem('dna-cart',JSON.stringify(cart))}
function notify(text){const t=$('#toast');if(!t)return;t.textContent=text;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1800)}
async function loadProducts(){try{const res=await fetch(root+'data/products.json',{cache:'no-store'});if(!res.ok)throw Error(res.status);products=await res.json()}catch(e){const g=$('#product-grid')||$('#detail-page');if(g)g.innerHTML='<p class="load-error">Không thể tải sản phẩm. Vui lòng chạy website qua máy chủ cục bộ và thử lại.</p>';throw e}}
function filtered(){let list=products.filter(p=>(filter==='Tất cả'||p.category===filter)&&p.name.toLowerCase().includes(query.toLowerCase())&&(brand==='all'||p.brand===brand)&&(scale==='all'||p.scale===scale)&&(!inStock||p.stock>0));list=list.filter(p=>price==='all'||price==='under-500'&&p.price<500000||price==='500-1000'&&p.price>=500000&&p.price<=1000000||price==='over-1000'&&p.price>1000000);if(sort==='newest')list.sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt));if(sort==='best-selling')list.sort((a,b)=>b.sold-a.sold);if(sort==='price-asc')list.sort((a,b)=>a.price-b.price);if(sort==='price-desc')list.sort((a,b)=>b.price-a.price);if(sort==='name')list.sort((a,b)=>a.name.localeCompare(b.name,'vi'));return list}
function card(p){const e=document.createElement('article');e.className='product';e.innerHTML=`<a class="product-view" href="${inPages?'':'pages/'}product-detail.html?id=${p.id}"><img src="${root+esc(p.image)}" alt="${esc(p.name)}" loading="lazy"></a>${p.tag?`<span class="tag">${esc(p.tag)}</span>`:''}<div class="info"><small>${esc(p.category)} · ${esc(p.brand)}</small><h3><a href="${inPages?'':'pages/'}product-detail.html?id=${p.id}">${esc(p.name)}</a></h3><p class="stock ${p.stock?'':'out'}">${p.stock?'Còn '+p.stock+' sản phẩm':'Tạm hết hàng'}</p><div class="price"><b>${money(p.price)}</b><button class="add" data-add="${p.id}" ${p.stock?'':'disabled'} aria-label="Thêm ${esc(p.name)}">+</button></div></div>`;return e}
function renderProducts(){const g=$('#product-grid');if(!g)return;let list=filtered();if(document.body.dataset.page==='detail')list=list.filter(p=>p.id!==+new URLSearchParams(location.search).get('id'));const homeLimit=+g.dataset.limit||0,shown=homeLimit?list.slice(0,homeLimit):list.slice(0,visible);g.replaceChildren(...shown.map(card));if(!list.length){const p=document.createElement('p');p.className='load-error';p.textContent='Không tìm thấy sản phẩm phù hợp.';g.append(p)}if($('#result-count'))$('#result-count').textContent=`Hiển thị ${shown.length} / ${list.length} sản phẩm`;if($('#load-more'))$('#load-more').hidden=shown.length>=list.length}
function change(id,d){const p=products.find(x=>x.id===id);if(!p||!p.stock)return;cart[id]=Math.max(0,Math.min(p.stock,(cart[id]||0)+d));if(!cart[id])delete cart[id];saveCart();renderCart()}
function cartRows(){return Object.entries(cart).map(([id,q])=>[products.find(p=>p.id===+id),q]).filter(x=>x[0])}
function renderCart(){const count=$('#cart-count'),box=$('#cart-items'),total=$('#cart-total'),rows=cartRows();if(count)count.textContent=rows.reduce((s,x)=>s+x[1],0);if(box){box.replaceChildren();if(!rows.length){const p=document.createElement('p');p.className='empty';p.textContent='Giỏ hàng đang trống. Hãy chọn một món thật ngầu nhé!';box.append(p)}else rows.forEach(([p,q])=>{const e=document.createElement('div');e.className='item';e.innerHTML=`<img class="thumb" src="${root+esc(p.image)}" alt=""><div><h3>${esc(p.name)}</h3><p>${money(p.price)}</p><div class="quantity"><button data-change="-1" data-id="${p.id}">−</button><b>${q}</b><button data-change="1" data-id="${p.id}">+</button><button class="remove" data-remove="${p.id}">Xóa</button></div></div>`;box.append(e)})}if(total)total.textContent=money(rows.reduce((s,[p,q])=>s+p.price*q,0));renderCheckout(rows)}
function renderCheckout(rows){const box=$('#checkout-items');if(!box)return;if(!rows.length){location.replace('products.html');return}box.innerHTML=rows.map(([p,q])=>`<div class="summary-item"><img src="${root+esc(p.image)}" alt=""><div><b>${esc(p.name)}</b><span>Số lượng: ${q}</span></div><strong>${money(p.price*q)}</strong></div>`).join('');const sub=rows.reduce((s,[p,q])=>s+p.price*q,0),shipping=sub>=1500000?0:30000;$('#checkout-subtotal').textContent=money(sub);$('#checkout-shipping').textContent=shipping?'30.000₫':'Miễn phí';$('#checkout-total').textContent=money(sub+shipping)}
function drawer(show){$('#drawer')?.classList.toggle('open',show);$('#overlay')?.classList.toggle('open',show);document.body.classList.toggle('locked',show)}
function renderDetail(){const h=$('#detail-page');if(!h)return;const p=products.find(x=>x.id===+new URLSearchParams(location.search).get('id'));if(!p){h.innerHTML='<div class="not-found"><h1>Không tìm thấy sản phẩm</h1><a class="primary" href="products.html">Về danh sách →</a></div>';return}document.title=p.name+' | DNA Hobby Store';$('#crumb').textContent=p.name;h.innerHTML=`<div class="detail-gallery"><img src="${root+esc(p.image)}" alt="${esc(p.name)}"></div><div class="detail-copy"><p class="kicker">${esc(p.category)} / ${esc(p.brand)}</p><h1>${esc(p.name)}</h1><b class="detail-price">${money(p.price)}</b><p class="detail-desc">${esc(p.description)}</p><dl><div><dt>Tỉ lệ</dt><dd>${esc(p.scale)}</dd></div><div><dt>Chất liệu</dt><dd>${esc(p.material)}</dd></div><div><dt>Tình trạng</dt><dd>${p.stock?'Còn hàng':'Tạm hết hàng'}</dd></div></dl><div class="detail-buy"><button class="primary" data-add="${p.id}" ${p.stock?'':'disabled'}>Thêm vào giỏ →</button><span>${p.stock?'Còn '+p.stock+' sản phẩm':'Sản phẩm đang hết hàng'}</span></div><p class="shipping-note">✓ Đóng gói chuẩn collector　✓ Đổi trả trong 7 ngày</p></div>`}
function setupFilters(){const brands=[...new Set(products.map(p=>p.brand))].sort(),scales=[...new Set(products.map(p=>p.scale))];brands.forEach(x=>$('#brand-filter')?.add(new Option(x,x)));scales.forEach(x=>$('#scale-filter')?.add(new Option(x,x)));$$('.filters button').forEach(b=>b.classList.toggle('active',b.dataset.filter===filter))}
document.addEventListener('error',e=>{if(e.target.tagName==='IMG'&&e.target.src!==fallback)e.target.src=fallback},true);
document.addEventListener('click',e=>{const a=e.target.closest('[data-add]');if(a){change(+a.dataset.add,1);notify('Đã thêm vào giỏ hàng')}if(e.target.dataset.change)change(+e.target.dataset.id,+e.target.dataset.change);if(e.target.dataset.remove){delete cart[e.target.dataset.remove];saveCart();renderCart()}});
$('.filters')?.addEventListener('click',e=>{if(!e.target.dataset.filter)return;filter=e.target.dataset.filter;visible=8;$$('.filters button').forEach(b=>b.classList.toggle('active',b.dataset.filter===filter));renderProducts()});
$('#search-input')?.addEventListener('input',e=>{query=e.target.value.slice(0,60);visible=8;renderProducts()});$('#sort')?.addEventListener('change',e=>{sort=e.target.value;renderProducts()});$('#price-filter')?.addEventListener('change',e=>{price=e.target.value;visible=8;renderProducts()});$('#brand-filter')?.addEventListener('change',e=>{brand=e.target.value;visible=8;renderProducts()});$('#scale-filter')?.addEventListener('change',e=>{scale=e.target.value;visible=8;renderProducts()});$('#stock-filter')?.addEventListener('change',e=>{inStock=e.target.checked;visible=8;renderProducts()});$('#load-more')?.addEventListener('click',()=>{visible+=4;renderProducts()});
$('#reset-filters')?.addEventListener('click',()=>{filter='Tất cả';query='';price=brand=scale='all';inStock=false;visible=8;$('#search-input').value='';$('#price-filter').value=$('#brand-filter').value=$('#scale-filter').value='all';$('#stock-filter').checked=false;$$('.filters button').forEach(b=>b.classList.toggle('active',b.dataset.filter==='Tất cả'));renderProducts()});
$('#cart-toggle')?.addEventListener('click',()=>drawer(true));$('#close-cart')?.addEventListener('click',()=>drawer(false));$('#overlay')?.addEventListener('click',()=>drawer(false));$('#menu')?.addEventListener('click',()=>$('#nav').classList.toggle('open'));$('#checkout')?.addEventListener('click',()=>Object.keys(cart).length?location.href=(inPages?'':'pages/')+'checkout.html':notify('Giỏ hàng đang trống'));
$('#checkout-form')?.addEventListener('submit',e=>{e.preventDefault();if(!e.target.reportValidity())return;cart={};saveCart();e.target.reset();notify('Đơn hàng mẫu đã được xác nhận');setTimeout(()=>location.href='../index.html',1200)});
(async()=>{try{await loadProducts();setupFilters();renderDetail();renderProducts();renderCart()}catch{}})();
